import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Main from "@/components/main";
import Categories from "@/app/categories/page";
import Promotion from "@/app/promotion/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <Header />
        <main>
          <Main />
        </main>
        <main>
          <Categories />
        </main>
        <main>
          <Promotion />
        </main>
        {children}
      </body>
    </html>
  );
}
